/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddChargeArgs {
  'description' : string,
  'folioId' : EntityId,
  'category' : ChargeCategory,
  'amount' : number,
}
export interface AddPaymentArgs {
  'method' : PaymentMethod,
  'referenceId' : string,
  'folioId' : EntityId,
  'amount' : number,
}
export interface AnalyticsData {
  'adr' : number,
  'revpar' : number,
  'revenueByRoomType' : Array<RevenueByRoomType>,
  'hotelId' : EntityId,
  'overallOccupancyPercent' : number,
  'revenueByMonth' : Array<MonthlyRevenue>,
  'occupancyByMonth' : Array<MonthlyOccupancy>,
  'totalRevenue' : number,
}
export type BookingSource = { 'OTA' : null } |
  { 'WalkIn' : null } |
  { 'Direct' : null };
export type BookingStatus = { 'CheckedIn' : null } |
  { 'NoShow' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'CheckedOut' : null } |
  { 'Pending' : null };
export interface BookingView {
  'id' : EntityId,
  'status' : BookingStatus,
  'actualCheckIn' : [] | [Timestamp],
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'createdAt' : Timestamp,
  'earlyCheckIn' : boolean,
  'hotelId' : EntityId,
  'guestName' : string,
  'guestEmail' : string,
  'lateCheckOut' : boolean,
  'numGuests' : bigint,
  'notes' : string,
  'checkOut' : Timestamp,
  'guestPhone' : string,
  'roomId' : EntityId,
  'actualCheckOut' : [] | [Timestamp],
  'guestId' : EntityId,
}
export interface ChannelConfigView {
  'id' : EntityId,
  'hotelId' : EntityId,
  'isActive' : boolean,
  'overbookingProtection' : boolean,
  'rateOverride' : [] | [number],
  'channel' : OTAChannel,
  'lastSync' : [] | [Timestamp],
  'syncStatus' : SyncStatus,
  'baseRate' : number,
}
export type ChargeCategory = { 'Tax' : null } |
  { 'Extra' : null } |
  { 'Room' : null } |
  { 'Discount' : null };
export interface CreateBookingArgs {
  'status' : BookingStatus,
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'earlyCheckIn' : boolean,
  'hotelId' : EntityId,
  'guestName' : string,
  'guestEmail' : string,
  'lateCheckOut' : boolean,
  'numGuests' : bigint,
  'notes' : string,
  'checkOut' : Timestamp,
  'guestPhone' : string,
  'roomId' : EntityId,
  'guestId' : EntityId,
}
export interface CreateChannelConfigArgs {
  'hotelId' : EntityId,
  'overbookingProtection' : boolean,
  'rateOverride' : [] | [number],
  'channel' : OTAChannel,
  'baseRate' : number,
}
export interface CreateFolioArgs {
  'bookingId' : EntityId,
  'hotelId' : EntityId,
  'guestId' : EntityId,
}
export interface CreateGuestArgs {
  'country' : string,
  'name' : string,
  'tags' : Array<GuestTag>,
  'email' : string,
  'preferences' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface CreateHotelArgs {
  'city' : string,
  'name' : string,
  'checkInTime' : string,
  'email' : string,
  'currency' : string,
  'address' : string,
  'checkOutTime' : string,
  'phone' : string,
  'totalRooms' : bigint,
}
export interface CreateHousekeepingTaskArgs {
  'assignedStaffId' : [] | [EntityId],
  'hotelId' : EntityId,
  'notes' : string,
  'priority' : bigint,
  'roomId' : EntityId,
}
export interface CreateRoomArgs {
  'floor' : bigint,
  'pricePerNight' : number,
  'hotelId' : EntityId,
  'amenities' : Array<string>,
  'number' : string,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export interface CreateStaffArgs {
  'name' : string,
  'role' : StaffRole,
  'hotelId' : EntityId,
  'email' : string,
  'phone' : string,
}
export type EntityId = bigint;
export interface FolioCharge {
  'id' : EntityId,
  'date' : Timestamp,
  'description' : string,
  'category' : ChargeCategory,
  'amount' : number,
}
export type FolioStatus = { 'Open' : null } |
  { 'Settled' : null };
export interface FolioView {
  'id' : EntityId,
  'status' : FolioStatus,
  'bookingId' : EntityId,
  'payments' : Array<Payment>,
  'hotelId' : EntityId,
  'charges' : Array<FolioCharge>,
  'guestId' : EntityId,
}
export type GuestTag = { 'New' : null } |
  { 'VIP' : null } |
  { 'Regular' : null } |
  { 'Corporate' : null };
export interface GuestView {
  'id' : EntityId,
  'country' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<GuestTag>,
  'email' : string,
  'loyaltyPoints' : bigint,
  'preferences' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface HotelView {
  'id' : EntityId,
  'city' : string,
  'name' : string,
  'checkInTime' : string,
  'email' : string,
  'currency' : string,
  'address' : string,
  'checkOutTime' : string,
  'phone' : string,
  'totalRooms' : bigint,
}
export interface HousekeepingTaskView {
  'id' : EntityId,
  'status' : TaskStatus,
  'completedAt' : [] | [Timestamp],
  'assignedStaffId' : [] | [EntityId],
  'createdAt' : Timestamp,
  'hotelId' : EntityId,
  'notes' : string,
  'priority' : bigint,
  'roomId' : EntityId,
}
export interface MonthlyOccupancy {
  'occupiedRooms' : bigint,
  'month' : bigint,
  'occupancyPercent' : number,
  'year' : bigint,
  'totalRooms' : bigint,
}
export interface MonthlyRevenue {
  'month' : bigint,
  'revenue' : number,
  'year' : bigint,
}
export type OTAChannel = { 'Airbnb' : null } |
  { 'MakeMyTrip' : null } |
  { 'BookingCom' : null } |
  { 'Expedia' : null } |
  { 'Direct' : null };
export interface Payment {
  'id' : EntityId,
  'method' : PaymentMethod,
  'date' : Timestamp,
  'referenceId' : string,
  'amount' : number,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null } |
  { 'BankTransfer' : null };
export interface RevenueByRoomType {
  'revenue' : number,
  'roomType' : RoomType,
  'bookingCount' : bigint,
}
export type RoomStatus = { 'OutOfOrder' : null } |
  { 'Dirty' : null } |
  { 'Maintenance' : null } |
  { 'Clean' : null } |
  { 'Occupied' : null };
export type RoomType = { 'Suite' : null } |
  { 'Presidential' : null } |
  { 'Deluxe' : null } |
  { 'Standard' : null };
export interface RoomView {
  'id' : EntityId,
  'floor' : bigint,
  'status' : RoomStatus,
  'pricePerNight' : number,
  'hotelId' : EntityId,
  'amenities' : Array<string>,
  'isActive' : boolean,
  'number' : string,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export type StaffRole = { 'FrontDesk' : null } |
  { 'Admin' : null } |
  { 'Housekeeping' : null } |
  { 'Manager' : null };
export type StaffStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface StaffView {
  'id' : EntityId,
  'status' : StaffStatus,
  'name' : string,
  'role' : StaffRole,
  'hotelId' : EntityId,
  'email' : string,
  'phone' : string,
}
export type SyncStatus = { 'Synced' : null } |
  { 'OutOfSync' : null };
export type TaskStatus = { 'Done' : null } |
  { 'InProgress' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface UpdateBookingArgs {
  'id' : EntityId,
  'status' : BookingStatus,
  'actualCheckIn' : [] | [Timestamp],
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'earlyCheckIn' : boolean,
  'guestName' : string,
  'guestEmail' : string,
  'lateCheckOut' : boolean,
  'numGuests' : bigint,
  'notes' : string,
  'checkOut' : Timestamp,
  'guestPhone' : string,
  'roomId' : EntityId,
  'actualCheckOut' : [] | [Timestamp],
}
export interface UpdateChannelConfigArgs {
  'id' : EntityId,
  'isActive' : boolean,
  'overbookingProtection' : boolean,
  'rateOverride' : [] | [number],
  'syncStatus' : SyncStatus,
  'baseRate' : number,
}
export interface UpdateGuestArgs {
  'id' : EntityId,
  'country' : string,
  'name' : string,
  'tags' : Array<GuestTag>,
  'email' : string,
  'loyaltyPoints' : bigint,
  'preferences' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface UpdateHotelArgs {
  'id' : EntityId,
  'city' : string,
  'name' : string,
  'checkInTime' : string,
  'email' : string,
  'currency' : string,
  'address' : string,
  'checkOutTime' : string,
  'phone' : string,
  'totalRooms' : bigint,
}
export interface UpdateHousekeepingTaskArgs {
  'id' : EntityId,
  'status' : TaskStatus,
  'completedAt' : [] | [Timestamp],
  'assignedStaffId' : [] | [EntityId],
  'notes' : string,
  'priority' : bigint,
  'roomId' : EntityId,
}
export interface UpdateRoomArgs {
  'id' : EntityId,
  'floor' : bigint,
  'status' : RoomStatus,
  'pricePerNight' : number,
  'amenities' : Array<string>,
  'isActive' : boolean,
  'number' : string,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export interface UpdateStaffArgs {
  'id' : EntityId,
  'status' : StaffStatus,
  'name' : string,
  'role' : StaffRole,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addFolioCharge' : ActorMethod<[AddChargeArgs], boolean>,
  'addFolioPayment' : ActorMethod<[AddPaymentArgs], boolean>,
  'checkInBooking' : ActorMethod<[EntityId], boolean>,
  'checkOutBooking' : ActorMethod<[EntityId], boolean>,
  'createBooking' : ActorMethod<[CreateBookingArgs], BookingView>,
  'createChannelConfig' : ActorMethod<
    [CreateChannelConfigArgs],
    ChannelConfigView
  >,
  'createFolio' : ActorMethod<[CreateFolioArgs], FolioView>,
  'createGuest' : ActorMethod<[CreateGuestArgs], GuestView>,
  'createHotel' : ActorMethod<[CreateHotelArgs], HotelView>,
  'createHousekeepingTask' : ActorMethod<
    [CreateHousekeepingTaskArgs],
    HousekeepingTaskView
  >,
  'createRoom' : ActorMethod<[CreateRoomArgs], RoomView>,
  'createStaff' : ActorMethod<[CreateStaffArgs], StaffView>,
  'deleteBooking' : ActorMethod<[EntityId], boolean>,
  'deleteChannelConfig' : ActorMethod<[EntityId], boolean>,
  'deleteGuest' : ActorMethod<[EntityId], boolean>,
  'deleteHotel' : ActorMethod<[EntityId], boolean>,
  'deleteHousekeepingTask' : ActorMethod<[EntityId], boolean>,
  'deleteRoom' : ActorMethod<[EntityId], boolean>,
  'deleteStaff' : ActorMethod<[EntityId], boolean>,
  'getAnalyticsData' : ActorMethod<
    [EntityId, bigint, bigint, bigint, bigint],
    AnalyticsData
  >,
  'getBooking' : ActorMethod<[EntityId], [] | [BookingView]>,
  'getBookings' : ActorMethod<[], Array<BookingView>>,
  'getBookingsByGuest' : ActorMethod<[EntityId], Array<BookingView>>,
  'getBookingsByHotel' : ActorMethod<[EntityId], Array<BookingView>>,
  'getChannelConfig' : ActorMethod<[EntityId], [] | [ChannelConfigView]>,
  'getChannelConfigs' : ActorMethod<[], Array<ChannelConfigView>>,
  'getChannelConfigsByHotel' : ActorMethod<
    [EntityId],
    Array<ChannelConfigView>
  >,
  'getFolio' : ActorMethod<[EntityId], [] | [FolioView]>,
  'getFolioByBooking' : ActorMethod<[EntityId], [] | [FolioView]>,
  'getFoliosByHotel' : ActorMethod<[EntityId], Array<FolioView>>,
  'getGuest' : ActorMethod<[EntityId], [] | [GuestView]>,
  'getGuests' : ActorMethod<[], Array<GuestView>>,
  'getHotel' : ActorMethod<[EntityId], [] | [HotelView]>,
  'getHotels' : ActorMethod<[], Array<HotelView>>,
  'getHousekeepingTask' : ActorMethod<[EntityId], [] | [HousekeepingTaskView]>,
  'getHousekeepingTasks' : ActorMethod<[], Array<HousekeepingTaskView>>,
  'getHousekeepingTasksByHotel' : ActorMethod<
    [EntityId],
    Array<HousekeepingTaskView>
  >,
  'getRoom' : ActorMethod<[EntityId], [] | [RoomView]>,
  'getRooms' : ActorMethod<[], Array<RoomView>>,
  'getRoomsByHotel' : ActorMethod<[EntityId], Array<RoomView>>,
  'getStaff' : ActorMethod<[], Array<StaffView>>,
  'getStaffByHotel' : ActorMethod<[EntityId], Array<StaffView>>,
  'getStaffMember' : ActorMethod<[EntityId], [] | [StaffView]>,
  'searchGuests' : ActorMethod<[string], Array<GuestView>>,
  'settleFolio' : ActorMethod<[EntityId], boolean>,
  'updateBooking' : ActorMethod<[UpdateBookingArgs], boolean>,
  'updateBookingStatus' : ActorMethod<[EntityId, BookingStatus], boolean>,
  'updateChannelConfig' : ActorMethod<[UpdateChannelConfigArgs], boolean>,
  'updateGuest' : ActorMethod<[UpdateGuestArgs], boolean>,
  'updateHotel' : ActorMethod<[UpdateHotelArgs], boolean>,
  'updateHousekeepingTask' : ActorMethod<[UpdateHousekeepingTaskArgs], boolean>,
  'updateHousekeepingTaskStatus' : ActorMethod<[EntityId, TaskStatus], boolean>,
  'updateRoom' : ActorMethod<[UpdateRoomArgs], boolean>,
  'updateRoomStatus' : ActorMethod<[EntityId, RoomStatus], boolean>,
  'updateStaff' : ActorMethod<[UpdateStaffArgs], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];