/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntityId = IDL.Nat;
export const ChargeCategory = IDL.Variant({
  'Tax' : IDL.Null,
  'Extra' : IDL.Null,
  'Room' : IDL.Null,
  'Discount' : IDL.Null,
});
export const AddChargeArgs = IDL.Record({
  'description' : IDL.Text,
  'folioId' : EntityId,
  'category' : ChargeCategory,
  'amount' : IDL.Float64,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'BankTransfer' : IDL.Null,
});
export const AddPaymentArgs = IDL.Record({
  'method' : PaymentMethod,
  'referenceId' : IDL.Text,
  'folioId' : EntityId,
  'amount' : IDL.Float64,
});
export const BookingStatus = IDL.Variant({
  'CheckedIn' : IDL.Null,
  'NoShow' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'CheckedOut' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const BookingSource = IDL.Variant({
  'OTA' : IDL.Null,
  'WalkIn' : IDL.Null,
  'Direct' : IDL.Null,
});
export const CreateBookingArgs = IDL.Record({
  'status' : BookingStatus,
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'earlyCheckIn' : IDL.Bool,
  'hotelId' : EntityId,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'lateCheckOut' : IDL.Bool,
  'numGuests' : IDL.Nat,
  'notes' : IDL.Text,
  'checkOut' : Timestamp,
  'guestPhone' : IDL.Text,
  'roomId' : EntityId,
  'guestId' : EntityId,
});
export const BookingView = IDL.Record({
  'id' : EntityId,
  'status' : BookingStatus,
  'actualCheckIn' : IDL.Opt(Timestamp),
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'createdAt' : Timestamp,
  'earlyCheckIn' : IDL.Bool,
  'hotelId' : EntityId,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'lateCheckOut' : IDL.Bool,
  'numGuests' : IDL.Nat,
  'notes' : IDL.Text,
  'checkOut' : Timestamp,
  'guestPhone' : IDL.Text,
  'roomId' : EntityId,
  'actualCheckOut' : IDL.Opt(Timestamp),
  'guestId' : EntityId,
});
export const OTAChannel = IDL.Variant({
  'Airbnb' : IDL.Null,
  'MakeMyTrip' : IDL.Null,
  'BookingCom' : IDL.Null,
  'Expedia' : IDL.Null,
  'Direct' : IDL.Null,
});
export const CreateChannelConfigArgs = IDL.Record({
  'hotelId' : EntityId,
  'overbookingProtection' : IDL.Bool,
  'rateOverride' : IDL.Opt(IDL.Float64),
  'channel' : OTAChannel,
  'baseRate' : IDL.Float64,
});
export const SyncStatus = IDL.Variant({
  'Synced' : IDL.Null,
  'OutOfSync' : IDL.Null,
});
export const ChannelConfigView = IDL.Record({
  'id' : EntityId,
  'hotelId' : EntityId,
  'isActive' : IDL.Bool,
  'overbookingProtection' : IDL.Bool,
  'rateOverride' : IDL.Opt(IDL.Float64),
  'channel' : OTAChannel,
  'lastSync' : IDL.Opt(Timestamp),
  'syncStatus' : SyncStatus,
  'baseRate' : IDL.Float64,
});
export const CreateFolioArgs = IDL.Record({
  'bookingId' : EntityId,
  'hotelId' : EntityId,
  'guestId' : EntityId,
});
export const FolioStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Settled' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : EntityId,
  'method' : PaymentMethod,
  'date' : Timestamp,
  'referenceId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FolioCharge = IDL.Record({
  'id' : EntityId,
  'date' : Timestamp,
  'description' : IDL.Text,
  'category' : ChargeCategory,
  'amount' : IDL.Float64,
});
export const FolioView = IDL.Record({
  'id' : EntityId,
  'status' : FolioStatus,
  'bookingId' : EntityId,
  'payments' : IDL.Vec(Payment),
  'hotelId' : EntityId,
  'charges' : IDL.Vec(FolioCharge),
  'guestId' : EntityId,
});
export const GuestTag = IDL.Variant({
  'New' : IDL.Null,
  'VIP' : IDL.Null,
  'Regular' : IDL.Null,
  'Corporate' : IDL.Null,
});
export const CreateGuestArgs = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(GuestTag),
  'email' : IDL.Text,
  'preferences' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const GuestView = IDL.Record({
  'id' : EntityId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(GuestTag),
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'preferences' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const CreateHotelArgs = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'checkInTime' : IDL.Text,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'phone' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const HotelView = IDL.Record({
  'id' : EntityId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'checkInTime' : IDL.Text,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'phone' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const CreateHousekeepingTaskArgs = IDL.Record({
  'assignedStaffId' : IDL.Opt(EntityId),
  'hotelId' : EntityId,
  'notes' : IDL.Text,
  'priority' : IDL.Nat,
  'roomId' : EntityId,
});
export const TaskStatus = IDL.Variant({
  'Done' : IDL.Null,
  'InProgress' : IDL.Null,
  'Pending' : IDL.Null,
});
export const HousekeepingTaskView = IDL.Record({
  'id' : EntityId,
  'status' : TaskStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'assignedStaffId' : IDL.Opt(EntityId),
  'createdAt' : Timestamp,
  'hotelId' : EntityId,
  'notes' : IDL.Text,
  'priority' : IDL.Nat,
  'roomId' : EntityId,
});
export const RoomType = IDL.Variant({
  'Suite' : IDL.Null,
  'Presidential' : IDL.Null,
  'Deluxe' : IDL.Null,
  'Standard' : IDL.Null,
});
export const CreateRoomArgs = IDL.Record({
  'floor' : IDL.Nat,
  'pricePerNight' : IDL.Float64,
  'hotelId' : EntityId,
  'amenities' : IDL.Vec(IDL.Text),
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const RoomStatus = IDL.Variant({
  'OutOfOrder' : IDL.Null,
  'Dirty' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Clean' : IDL.Null,
  'Occupied' : IDL.Null,
});
export const RoomView = IDL.Record({
  'id' : EntityId,
  'floor' : IDL.Nat,
  'status' : RoomStatus,
  'pricePerNight' : IDL.Float64,
  'hotelId' : EntityId,
  'amenities' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const StaffRole = IDL.Variant({
  'FrontDesk' : IDL.Null,
  'Admin' : IDL.Null,
  'Housekeeping' : IDL.Null,
  'Manager' : IDL.Null,
});
export const CreateStaffArgs = IDL.Record({
  'name' : IDL.Text,
  'role' : StaffRole,
  'hotelId' : EntityId,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StaffStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const StaffView = IDL.Record({
  'id' : EntityId,
  'status' : StaffStatus,
  'name' : IDL.Text,
  'role' : StaffRole,
  'hotelId' : EntityId,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RevenueByRoomType = IDL.Record({
  'revenue' : IDL.Float64,
  'roomType' : RoomType,
  'bookingCount' : IDL.Nat,
});
export const MonthlyRevenue = IDL.Record({
  'month' : IDL.Nat,
  'revenue' : IDL.Float64,
  'year' : IDL.Nat,
});
export const MonthlyOccupancy = IDL.Record({
  'occupiedRooms' : IDL.Nat,
  'month' : IDL.Nat,
  'occupancyPercent' : IDL.Float64,
  'year' : IDL.Nat,
  'totalRooms' : IDL.Nat,
});
export const AnalyticsData = IDL.Record({
  'adr' : IDL.Float64,
  'revpar' : IDL.Float64,
  'revenueByRoomType' : IDL.Vec(RevenueByRoomType),
  'hotelId' : EntityId,
  'overallOccupancyPercent' : IDL.Float64,
  'revenueByMonth' : IDL.Vec(MonthlyRevenue),
  'occupancyByMonth' : IDL.Vec(MonthlyOccupancy),
  'totalRevenue' : IDL.Float64,
});
export const UpdateBookingArgs = IDL.Record({
  'id' : EntityId,
  'status' : BookingStatus,
  'actualCheckIn' : IDL.Opt(Timestamp),
  'checkIn' : Timestamp,
  'source' : BookingSource,
  'earlyCheckIn' : IDL.Bool,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'lateCheckOut' : IDL.Bool,
  'numGuests' : IDL.Nat,
  'notes' : IDL.Text,
  'checkOut' : Timestamp,
  'guestPhone' : IDL.Text,
  'roomId' : EntityId,
  'actualCheckOut' : IDL.Opt(Timestamp),
});
export const UpdateChannelConfigArgs = IDL.Record({
  'id' : EntityId,
  'isActive' : IDL.Bool,
  'overbookingProtection' : IDL.Bool,
  'rateOverride' : IDL.Opt(IDL.Float64),
  'syncStatus' : SyncStatus,
  'baseRate' : IDL.Float64,
});
export const UpdateGuestArgs = IDL.Record({
  'id' : EntityId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(GuestTag),
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'preferences' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateHotelArgs = IDL.Record({
  'id' : EntityId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'checkInTime' : IDL.Text,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'phone' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const UpdateHousekeepingTaskArgs = IDL.Record({
  'id' : EntityId,
  'status' : TaskStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'assignedStaffId' : IDL.Opt(EntityId),
  'notes' : IDL.Text,
  'priority' : IDL.Nat,
  'roomId' : EntityId,
});
export const UpdateRoomArgs = IDL.Record({
  'id' : EntityId,
  'floor' : IDL.Nat,
  'status' : RoomStatus,
  'pricePerNight' : IDL.Float64,
  'amenities' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'number' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const UpdateStaffArgs = IDL.Record({
  'id' : EntityId,
  'status' : StaffStatus,
  'name' : IDL.Text,
  'role' : StaffRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFolioCharge' : IDL.Func([AddChargeArgs], [IDL.Bool], []),
  'addFolioPayment' : IDL.Func([AddPaymentArgs], [IDL.Bool], []),
  'checkInBooking' : IDL.Func([EntityId], [IDL.Bool], []),
  'checkOutBooking' : IDL.Func([EntityId], [IDL.Bool], []),
  'createBooking' : IDL.Func([CreateBookingArgs], [BookingView], []),
  'createChannelConfig' : IDL.Func(
      [CreateChannelConfigArgs],
      [ChannelConfigView],
      [],
    ),
  'createFolio' : IDL.Func([CreateFolioArgs], [FolioView], []),
  'createGuest' : IDL.Func([CreateGuestArgs], [GuestView], []),
  'createHotel' : IDL.Func([CreateHotelArgs], [HotelView], []),
  'createHousekeepingTask' : IDL.Func(
      [CreateHousekeepingTaskArgs],
      [HousekeepingTaskView],
      [],
    ),
  'createRoom' : IDL.Func([CreateRoomArgs], [RoomView], []),
  'createStaff' : IDL.Func([CreateStaffArgs], [StaffView], []),
  'deleteBooking' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteChannelConfig' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteGuest' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteHotel' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteHousekeepingTask' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteRoom' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteStaff' : IDL.Func([EntityId], [IDL.Bool], []),
  'getAnalyticsData' : IDL.Func(
      [EntityId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [AnalyticsData],
      ['query'],
    ),
  'getBooking' : IDL.Func([EntityId], [IDL.Opt(BookingView)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'getBookingsByGuest' : IDL.Func(
      [EntityId],
      [IDL.Vec(BookingView)],
      ['query'],
    ),
  'getBookingsByHotel' : IDL.Func(
      [EntityId],
      [IDL.Vec(BookingView)],
      ['query'],
    ),
  'getChannelConfig' : IDL.Func(
      [EntityId],
      [IDL.Opt(ChannelConfigView)],
      ['query'],
    ),
  'getChannelConfigs' : IDL.Func([], [IDL.Vec(ChannelConfigView)], ['query']),
  'getChannelConfigsByHotel' : IDL.Func(
      [EntityId],
      [IDL.Vec(ChannelConfigView)],
      ['query'],
    ),
  'getFolio' : IDL.Func([EntityId], [IDL.Opt(FolioView)], ['query']),
  'getFolioByBooking' : IDL.Func([EntityId], [IDL.Opt(FolioView)], ['query']),
  'getFoliosByHotel' : IDL.Func([EntityId], [IDL.Vec(FolioView)], ['query']),
  'getGuest' : IDL.Func([EntityId], [IDL.Opt(GuestView)], ['query']),
  'getGuests' : IDL.Func([], [IDL.Vec(GuestView)], ['query']),
  'getHotel' : IDL.Func([EntityId], [IDL.Opt(HotelView)], ['query']),
  'getHotels' : IDL.Func([], [IDL.Vec(HotelView)], ['query']),
  'getHousekeepingTask' : IDL.Func(
      [EntityId],
      [IDL.Opt(HousekeepingTaskView)],
      ['query'],
    ),
  'getHousekeepingTasks' : IDL.Func(
      [],
      [IDL.Vec(HousekeepingTaskView)],
      ['query'],
    ),
  'getHousekeepingTasksByHotel' : IDL.Func(
      [EntityId],
      [IDL.Vec(HousekeepingTaskView)],
      ['query'],
    ),
  'getRoom' : IDL.Func([EntityId], [IDL.Opt(RoomView)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getRoomsByHotel' : IDL.Func([EntityId], [IDL.Vec(RoomView)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(StaffView)], ['query']),
  'getStaffByHotel' : IDL.Func([EntityId], [IDL.Vec(StaffView)], ['query']),
  'getStaffMember' : IDL.Func([EntityId], [IDL.Opt(StaffView)], ['query']),
  'searchGuests' : IDL.Func([IDL.Text], [IDL.Vec(GuestView)], ['query']),
  'settleFolio' : IDL.Func([EntityId], [IDL.Bool], []),
  'updateBooking' : IDL.Func([UpdateBookingArgs], [IDL.Bool], []),
  'updateBookingStatus' : IDL.Func([EntityId, BookingStatus], [IDL.Bool], []),
  'updateChannelConfig' : IDL.Func([UpdateChannelConfigArgs], [IDL.Bool], []),
  'updateGuest' : IDL.Func([UpdateGuestArgs], [IDL.Bool], []),
  'updateHotel' : IDL.Func([UpdateHotelArgs], [IDL.Bool], []),
  'updateHousekeepingTask' : IDL.Func(
      [UpdateHousekeepingTaskArgs],
      [IDL.Bool],
      [],
    ),
  'updateHousekeepingTaskStatus' : IDL.Func(
      [EntityId, TaskStatus],
      [IDL.Bool],
      [],
    ),
  'updateRoom' : IDL.Func([UpdateRoomArgs], [IDL.Bool], []),
  'updateRoomStatus' : IDL.Func([EntityId, RoomStatus], [IDL.Bool], []),
  'updateStaff' : IDL.Func([UpdateStaffArgs], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntityId = IDL.Nat;
  const ChargeCategory = IDL.Variant({
    'Tax' : IDL.Null,
    'Extra' : IDL.Null,
    'Room' : IDL.Null,
    'Discount' : IDL.Null,
  });
  const AddChargeArgs = IDL.Record({
    'description' : IDL.Text,
    'folioId' : EntityId,
    'category' : ChargeCategory,
    'amount' : IDL.Float64,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'BankTransfer' : IDL.Null,
  });
  const AddPaymentArgs = IDL.Record({
    'method' : PaymentMethod,
    'referenceId' : IDL.Text,
    'folioId' : EntityId,
    'amount' : IDL.Float64,
  });
  const BookingStatus = IDL.Variant({
    'CheckedIn' : IDL.Null,
    'NoShow' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'CheckedOut' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const BookingSource = IDL.Variant({
    'OTA' : IDL.Null,
    'WalkIn' : IDL.Null,
    'Direct' : IDL.Null,
  });
  const CreateBookingArgs = IDL.Record({
    'status' : BookingStatus,
    'checkIn' : Timestamp,
    'source' : BookingSource,
    'earlyCheckIn' : IDL.Bool,
    'hotelId' : EntityId,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'lateCheckOut' : IDL.Bool,
    'numGuests' : IDL.Nat,
    'notes' : IDL.Text,
    'checkOut' : Timestamp,
    'guestPhone' : IDL.Text,
    'roomId' : EntityId,
    'guestId' : EntityId,
  });
  const BookingView = IDL.Record({
    'id' : EntityId,
    'status' : BookingStatus,
    'actualCheckIn' : IDL.Opt(Timestamp),
    'checkIn' : Timestamp,
    'source' : BookingSource,
    'createdAt' : Timestamp,
    'earlyCheckIn' : IDL.Bool,
    'hotelId' : EntityId,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'lateCheckOut' : IDL.Bool,
    'numGuests' : IDL.Nat,
    'notes' : IDL.Text,
    'checkOut' : Timestamp,
    'guestPhone' : IDL.Text,
    'roomId' : EntityId,
    'actualCheckOut' : IDL.Opt(Timestamp),
    'guestId' : EntityId,
  });
  const OTAChannel = IDL.Variant({
    'Airbnb' : IDL.Null,
    'MakeMyTrip' : IDL.Null,
    'BookingCom' : IDL.Null,
    'Expedia' : IDL.Null,
    'Direct' : IDL.Null,
  });
  const CreateChannelConfigArgs = IDL.Record({
    'hotelId' : EntityId,
    'overbookingProtection' : IDL.Bool,
    'rateOverride' : IDL.Opt(IDL.Float64),
    'channel' : OTAChannel,
    'baseRate' : IDL.Float64,
  });
  const SyncStatus = IDL.Variant({
    'Synced' : IDL.Null,
    'OutOfSync' : IDL.Null,
  });
  const ChannelConfigView = IDL.Record({
    'id' : EntityId,
    'hotelId' : EntityId,
    'isActive' : IDL.Bool,
    'overbookingProtection' : IDL.Bool,
    'rateOverride' : IDL.Opt(IDL.Float64),
    'channel' : OTAChannel,
    'lastSync' : IDL.Opt(Timestamp),
    'syncStatus' : SyncStatus,
    'baseRate' : IDL.Float64,
  });
  const CreateFolioArgs = IDL.Record({
    'bookingId' : EntityId,
    'hotelId' : EntityId,
    'guestId' : EntityId,
  });
  const FolioStatus = IDL.Variant({ 'Open' : IDL.Null, 'Settled' : IDL.Null });
  const Payment = IDL.Record({
    'id' : EntityId,
    'method' : PaymentMethod,
    'date' : Timestamp,
    'referenceId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FolioCharge = IDL.Record({
    'id' : EntityId,
    'date' : Timestamp,
    'description' : IDL.Text,
    'category' : ChargeCategory,
    'amount' : IDL.Float64,
  });
  const FolioView = IDL.Record({
    'id' : EntityId,
    'status' : FolioStatus,
    'bookingId' : EntityId,
    'payments' : IDL.Vec(Payment),
    'hotelId' : EntityId,
    'charges' : IDL.Vec(FolioCharge),
    'guestId' : EntityId,
  });
  const GuestTag = IDL.Variant({
    'New' : IDL.Null,
    'VIP' : IDL.Null,
    'Regular' : IDL.Null,
    'Corporate' : IDL.Null,
  });
  const CreateGuestArgs = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(GuestTag),
    'email' : IDL.Text,
    'preferences' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GuestView = IDL.Record({
    'id' : EntityId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(GuestTag),
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'preferences' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CreateHotelArgs = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'checkInTime' : IDL.Text,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'phone' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const HotelView = IDL.Record({
    'id' : EntityId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'checkInTime' : IDL.Text,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'phone' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const CreateHousekeepingTaskArgs = IDL.Record({
    'assignedStaffId' : IDL.Opt(EntityId),
    'hotelId' : EntityId,
    'notes' : IDL.Text,
    'priority' : IDL.Nat,
    'roomId' : EntityId,
  });
  const TaskStatus = IDL.Variant({
    'Done' : IDL.Null,
    'InProgress' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const HousekeepingTaskView = IDL.Record({
    'id' : EntityId,
    'status' : TaskStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'assignedStaffId' : IDL.Opt(EntityId),
    'createdAt' : Timestamp,
    'hotelId' : EntityId,
    'notes' : IDL.Text,
    'priority' : IDL.Nat,
    'roomId' : EntityId,
  });
  const RoomType = IDL.Variant({
    'Suite' : IDL.Null,
    'Presidential' : IDL.Null,
    'Deluxe' : IDL.Null,
    'Standard' : IDL.Null,
  });
  const CreateRoomArgs = IDL.Record({
    'floor' : IDL.Nat,
    'pricePerNight' : IDL.Float64,
    'hotelId' : EntityId,
    'amenities' : IDL.Vec(IDL.Text),
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const RoomStatus = IDL.Variant({
    'OutOfOrder' : IDL.Null,
    'Dirty' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Clean' : IDL.Null,
    'Occupied' : IDL.Null,
  });
  const RoomView = IDL.Record({
    'id' : EntityId,
    'floor' : IDL.Nat,
    'status' : RoomStatus,
    'pricePerNight' : IDL.Float64,
    'hotelId' : EntityId,
    'amenities' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const StaffRole = IDL.Variant({
    'FrontDesk' : IDL.Null,
    'Admin' : IDL.Null,
    'Housekeeping' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const CreateStaffArgs = IDL.Record({
    'name' : IDL.Text,
    'role' : StaffRole,
    'hotelId' : EntityId,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StaffStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const StaffView = IDL.Record({
    'id' : EntityId,
    'status' : StaffStatus,
    'name' : IDL.Text,
    'role' : StaffRole,
    'hotelId' : EntityId,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RevenueByRoomType = IDL.Record({
    'revenue' : IDL.Float64,
    'roomType' : RoomType,
    'bookingCount' : IDL.Nat,
  });
  const MonthlyRevenue = IDL.Record({
    'month' : IDL.Nat,
    'revenue' : IDL.Float64,
    'year' : IDL.Nat,
  });
  const MonthlyOccupancy = IDL.Record({
    'occupiedRooms' : IDL.Nat,
    'month' : IDL.Nat,
    'occupancyPercent' : IDL.Float64,
    'year' : IDL.Nat,
    'totalRooms' : IDL.Nat,
  });
  const AnalyticsData = IDL.Record({
    'adr' : IDL.Float64,
    'revpar' : IDL.Float64,
    'revenueByRoomType' : IDL.Vec(RevenueByRoomType),
    'hotelId' : EntityId,
    'overallOccupancyPercent' : IDL.Float64,
    'revenueByMonth' : IDL.Vec(MonthlyRevenue),
    'occupancyByMonth' : IDL.Vec(MonthlyOccupancy),
    'totalRevenue' : IDL.Float64,
  });
  const UpdateBookingArgs = IDL.Record({
    'id' : EntityId,
    'status' : BookingStatus,
    'actualCheckIn' : IDL.Opt(Timestamp),
    'checkIn' : Timestamp,
    'source' : BookingSource,
    'earlyCheckIn' : IDL.Bool,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'lateCheckOut' : IDL.Bool,
    'numGuests' : IDL.Nat,
    'notes' : IDL.Text,
    'checkOut' : Timestamp,
    'guestPhone' : IDL.Text,
    'roomId' : EntityId,
    'actualCheckOut' : IDL.Opt(Timestamp),
  });
  const UpdateChannelConfigArgs = IDL.Record({
    'id' : EntityId,
    'isActive' : IDL.Bool,
    'overbookingProtection' : IDL.Bool,
    'rateOverride' : IDL.Opt(IDL.Float64),
    'syncStatus' : SyncStatus,
    'baseRate' : IDL.Float64,
  });
  const UpdateGuestArgs = IDL.Record({
    'id' : EntityId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(GuestTag),
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'preferences' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateHotelArgs = IDL.Record({
    'id' : EntityId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'checkInTime' : IDL.Text,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'phone' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const UpdateHousekeepingTaskArgs = IDL.Record({
    'id' : EntityId,
    'status' : TaskStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'assignedStaffId' : IDL.Opt(EntityId),
    'notes' : IDL.Text,
    'priority' : IDL.Nat,
    'roomId' : EntityId,
  });
  const UpdateRoomArgs = IDL.Record({
    'id' : EntityId,
    'floor' : IDL.Nat,
    'status' : RoomStatus,
    'pricePerNight' : IDL.Float64,
    'amenities' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'number' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const UpdateStaffArgs = IDL.Record({
    'id' : EntityId,
    'status' : StaffStatus,
    'name' : IDL.Text,
    'role' : StaffRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addFolioCharge' : IDL.Func([AddChargeArgs], [IDL.Bool], []),
    'addFolioPayment' : IDL.Func([AddPaymentArgs], [IDL.Bool], []),
    'checkInBooking' : IDL.Func([EntityId], [IDL.Bool], []),
    'checkOutBooking' : IDL.Func([EntityId], [IDL.Bool], []),
    'createBooking' : IDL.Func([CreateBookingArgs], [BookingView], []),
    'createChannelConfig' : IDL.Func(
        [CreateChannelConfigArgs],
        [ChannelConfigView],
        [],
      ),
    'createFolio' : IDL.Func([CreateFolioArgs], [FolioView], []),
    'createGuest' : IDL.Func([CreateGuestArgs], [GuestView], []),
    'createHotel' : IDL.Func([CreateHotelArgs], [HotelView], []),
    'createHousekeepingTask' : IDL.Func(
        [CreateHousekeepingTaskArgs],
        [HousekeepingTaskView],
        [],
      ),
    'createRoom' : IDL.Func([CreateRoomArgs], [RoomView], []),
    'createStaff' : IDL.Func([CreateStaffArgs], [StaffView], []),
    'deleteBooking' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteChannelConfig' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteGuest' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteHotel' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteHousekeepingTask' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteRoom' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteStaff' : IDL.Func([EntityId], [IDL.Bool], []),
    'getAnalyticsData' : IDL.Func(
        [EntityId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [AnalyticsData],
        ['query'],
      ),
    'getBooking' : IDL.Func([EntityId], [IDL.Opt(BookingView)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'getBookingsByGuest' : IDL.Func(
        [EntityId],
        [IDL.Vec(BookingView)],
        ['query'],
      ),
    'getBookingsByHotel' : IDL.Func(
        [EntityId],
        [IDL.Vec(BookingView)],
        ['query'],
      ),
    'getChannelConfig' : IDL.Func(
        [EntityId],
        [IDL.Opt(ChannelConfigView)],
        ['query'],
      ),
    'getChannelConfigs' : IDL.Func([], [IDL.Vec(ChannelConfigView)], ['query']),
    'getChannelConfigsByHotel' : IDL.Func(
        [EntityId],
        [IDL.Vec(ChannelConfigView)],
        ['query'],
      ),
    'getFolio' : IDL.Func([EntityId], [IDL.Opt(FolioView)], ['query']),
    'getFolioByBooking' : IDL.Func([EntityId], [IDL.Opt(FolioView)], ['query']),
    'getFoliosByHotel' : IDL.Func([EntityId], [IDL.Vec(FolioView)], ['query']),
    'getGuest' : IDL.Func([EntityId], [IDL.Opt(GuestView)], ['query']),
    'getGuests' : IDL.Func([], [IDL.Vec(GuestView)], ['query']),
    'getHotel' : IDL.Func([EntityId], [IDL.Opt(HotelView)], ['query']),
    'getHotels' : IDL.Func([], [IDL.Vec(HotelView)], ['query']),
    'getHousekeepingTask' : IDL.Func(
        [EntityId],
        [IDL.Opt(HousekeepingTaskView)],
        ['query'],
      ),
    'getHousekeepingTasks' : IDL.Func(
        [],
        [IDL.Vec(HousekeepingTaskView)],
        ['query'],
      ),
    'getHousekeepingTasksByHotel' : IDL.Func(
        [EntityId],
        [IDL.Vec(HousekeepingTaskView)],
        ['query'],
      ),
    'getRoom' : IDL.Func([EntityId], [IDL.Opt(RoomView)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getRoomsByHotel' : IDL.Func([EntityId], [IDL.Vec(RoomView)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(StaffView)], ['query']),
    'getStaffByHotel' : IDL.Func([EntityId], [IDL.Vec(StaffView)], ['query']),
    'getStaffMember' : IDL.Func([EntityId], [IDL.Opt(StaffView)], ['query']),
    'searchGuests' : IDL.Func([IDL.Text], [IDL.Vec(GuestView)], ['query']),
    'settleFolio' : IDL.Func([EntityId], [IDL.Bool], []),
    'updateBooking' : IDL.Func([UpdateBookingArgs], [IDL.Bool], []),
    'updateBookingStatus' : IDL.Func([EntityId, BookingStatus], [IDL.Bool], []),
    'updateChannelConfig' : IDL.Func([UpdateChannelConfigArgs], [IDL.Bool], []),
    'updateGuest' : IDL.Func([UpdateGuestArgs], [IDL.Bool], []),
    'updateHotel' : IDL.Func([UpdateHotelArgs], [IDL.Bool], []),
    'updateHousekeepingTask' : IDL.Func(
        [UpdateHousekeepingTaskArgs],
        [IDL.Bool],
        [],
      ),
    'updateHousekeepingTaskStatus' : IDL.Func(
        [EntityId, TaskStatus],
        [IDL.Bool],
        [],
      ),
    'updateRoom' : IDL.Func([UpdateRoomArgs], [IDL.Bool], []),
    'updateRoomStatus' : IDL.Func([EntityId, RoomStatus], [IDL.Bool], []),
    'updateStaff' : IDL.Func([UpdateStaffArgs], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };